name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set up JDK 21
      uses: actions/setup-java@main
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Gradle
      run: ./gradlew app:assembleRelease

    - name: Rename unsigned APK
      run: mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/Demo.apk

    - name: Generate keystore
      run: |
        keytool -genkeypair \
          -alias releaseKey \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -keystore demo-release-key.jks \
          -storepass demoPassword \
          -keypass demoPassword \
          -dname "CN=GitHub CI, OU=DevOps, O=GitHub, L=Internet, S=World, C=US"

    - name: Sign APK
      run: |
        /usr/local/lib/android/sdk/build-tools/34.0.0/apksigner sign \
          --ks demo-release-key.jks \
          --ks-key-alias releaseKey \
          --ks-pass pass:demoPassword \
          --key-pass pass:demoPassword \
          --out app/build/outputs/apk/release/Demo-signed.apk \
          app/build/outputs/apk/release/Demo.apk

    - name: Verify APK signature
      run: |
        /usr/local/lib/android/sdk/build-tools/34.0.0/apksigner verify \
          app/build/outputs/apk/release/Demo-signed.apk

    - name: Upload signed APK
      uses: actions/upload-artifact@main
      with:
        name: Demo-signed.apk
        path: app/build/outputs/apk/release/Demo-signed.apk
